spring.application.name=NammaPG

# MongoDB
spring.data.mongodb.uri=mongodb+srv://thoufiqaa11_db_user:hryw97GeiNkUyH9d@cluster0.lcsnxjw.mongodb.net/nammapg?appName=Cluster0

# JWT
jwt.secret=NammaPG_Super_Secret_Key_2024_Must_Be_At_Least_256_Bits_Long_For_HS256
jwt.expiration=86400000

# Server
server.port=8080